qyedu/new_admin/urls.py
# coding=utf-8
from django.urls import path
from . import views as admin_view
from django.views.decorators.cache import cache_page
app_name = 'new_admin'

# 登录相关
urlpatterns = [
    # 首页
    path('', admin_view.index, name='index'),
    # 登录
    path('login/', admin_view.login, name='login'),
    # 登录验证
    path('login_check/', admin_view.login_check, name='login_check'),
    # 欢迎页
    path('welcome/', admin_view.welcome, name='welcome'),
    # 退出登录
    path('logout_view/', admin_view.logout_view, name='logout_view'),
]

# 菜单
urlpatterns += [
    # 栏目列表
    path('category/', admin_view.category, name='category'),
    # 栏目添加
    path('category/add/', admin_view.category_add, name='category_add'),
    # 栏目添加验证
    path('category/add/check/', admin_view.category_add_check, name='category_add_check'),
    # 删除栏目
    path('category/del/', admin_view.category_del, name='category_del'),
    # 修改栏目
    path('category/category_modify/', admin_view.category_modify, name='category_modify'),
    # 修改栏目验证
    path('category/category_modify/check/', admin_view.category_modify_check, name='category_modify_check'),
]

# 宿舍
urlpatterns += [
    # 宿舍列表
    path('dorm/', admin_view.dorm, name='dorm'),
    # 宿舍添加
    path('dorm/add/', admin_view.dorm_add, name='dorm_add'),
    # 宿舍添加验证
    path('dorm/add/check', admin_view.dorm_add_check, name='dorm_add_check'),
    # 宿舍修改
    path('dorm/modify/', admin_view.dorm_modify, name='dorm_modify'),
    # 宿舍修改验证
    path('dorm/modify/check', admin_view.dorm_modify_check, name='dorm_modify_check'),
    # 宿舍删除
    path('dorm/del/', admin_view.dorm_del, name='dorm_del'),
]

# 管理员管理
urlpatterns += [
    # 管理员列表
    path('admin/', admin_view.admin, name='admin'),
    # 管理员添加
    path('admin/add/check/', admin_view.admin_add_check, name='admin_add_check'),
    # 管理员添加验证
    path('admin/add/', admin_view.admin_add, name='admin_add'),
    # 删除管理员
    path('admin/del/', admin_view.admin_del, name='admin_del'),
    # 修改管理员
    path('admin/modify/', admin_view.admin_modify, name='admin_modify'),
    # 修改管理员验证
    path('admin/modify/check/', admin_view.admin_modify_check, name='admin_modify_check'),
    # 管理员启用
    path('admin/start/', admin_view.admin_start, name='admin_start'),
    # 管理员停用
    path('admin/stop/', admin_view.admin_stop, name='admin_stop'),
    # 修改密码
    path('admin/pwd_edit/', admin_view.admin_pwd_edit, name='admin_pwd_edit'),
]

# 班级管理
urlpatterns += [
    # 班级列表
    path('classgrade/', admin_view.classgrade, name='classgrade'),
    # 班级添加
    path('classgrade/add/', admin_view.classgrade_add, name='classgrade_add'),
    # 班级添加验证
    path('classgrade/add/check/', admin_view.classgrade_add_check, name='classgrade_add_check'),
    # 班级删除
    path('classgrade/del/', admin_view.classsgrade_del, name='classgrade_del'),
    # 班级修改
    path('classgrade/modify/', admin_view.classgrade_modify, name='classgrade_modify'),
    # 班级修改保存
    path('classgrade/save/', admin_view.classgrade_save, name='classgrade_save'),
    # 班级搜索
    path('classgrade/search/', admin_view.classgrade_search, name='classgrade_search'),
]

# 学员
urlpatterns += [
    # 学员管理
    path('student_list/', admin_view.student_list, name="student_list"),
    # 学员信息修改
    path('student_amend/', admin_view.student_amend, name="student_amend"),
    # 修改判断
    path('student_check/', admin_view.student_check, name="student_check"),
    # 学员删除
    path("student_delete/", admin_view.student_delete, name="student_delete"),
    # 学员搜索判断
    path("student_query/", admin_view.student_query, name="student_query"),
]
# 结业模块
urlpatterns +=[
    # 违纪，处罚页面
    path("violate_punish/", cache_page(10)(admin_view.violate_punish),name="violate_punish"),
    # 违纪，处罚判断
    path("violate_punish_ckeck/", admin_view.violate_punish_ckeck,name="violate_punish_ckeck"),
    # 补贴页面
    path("subsidy/", cache_page(10)(admin_view.subsidy), name="subsidy"),
    # 补贴搜索
    path("subsidy_ckeck/", admin_view.subsidy_ckeck,name="subsidy_ckeck"),
    # 技能成绩页面
    path("skill_grade/", cache_page(10)(admin_view.skill_grade),name="skill_grade"),
    # 技能成绩搜索判断
    path("skill_grade_ckeck/", admin_view.skill_grade_ckeck,name="skill_grade_ckeck"),
    # 职业素养页面
    path("profession_grade/", cache_page(10)(admin_view.profession_grade),name="profession_grade"),
    # 职业素养页面判断
    path("profession_grade_ckeck/", admin_view.profession_grade_ckeck,name="profession_grade_ckeck"),
    # 能力评估页面
    path("appraisal_report/", cache_page(10)(admin_view.appraisal_report),name="appraisal_report"),
    # 能力评估收搜页面
    path("appraisal_report_ckeck/", admin_view.appraisal_report_ckeck,name="appraisal_report_ckeck"),
    # 能力评估详细
    path("appraisal_detail/", admin_view.appraisal_detail,name="appraisal_detail"),
    # 访谈记录页面
    path("interview_record/", cache_page(10)(admin_view.interview_record),name="interview_record"),
    # 访谈记录收搜判断
    path("interview_record_ckeck/",admin_view.interview_record_ckeck,name="interview_record_ckeck")
]

qyedu/qyedu/urls.py
# coding=utf8
# from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    # 授课
    path('give_lessons/', include('give_lessons.urls')),
    # 后台
    path('new_admin/', include('new_admin.urls')),
    # 学习
    path('study/', include('study.urls')),
    # 人才库
    path('talent_all/', include('talent_all.urls')),
    # path('admin/', admin.site.urls),
    # 宿舍
    path('dormitory/', include("dormitory.urls")),
    # 考试
    path('examination/', include("examination.urls")),
    # 第三方模块验证码相关
    path('captcha/', include('captcha.urls')),
    # 招生
    path('recruit_students/', include('recruit_students.urls')),
    # 就业
    path('job/', include('obtain_employment.urls')),
    # 训练营
    path('star/', include('six_group.urls')),
    # 访谈
    path('interview/', include('interview.urls')),
    # 评测
    path('evaluate/', include('evaluate.urls')),

]


urlpatterns += [
    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='media')
]

qyedu/six_group/urls.py
from django.urls import path
from . import views as admin_view


app_name = 'six_group'
urlpatterns = [
    # 训练营
    path('training_camp/', admin_view.training_camp, name='training_camp'),
    # 分配班级
    path('allocation_class/', admin_view.allocation_class, name='allocation_class'),
    # 分配班级验证
    path('allocation_class_check/', admin_view.allocation_class_check, name='allocation_class_check'),
    # 激活
    path('activate_state/', admin_view.activate_state, name='activate_state'),
    # 激活验证
    path('activate_state_check/', admin_view.activate_state_check, name='activate_state_check'),
    # 放弃
    path('activate_state_not/', admin_view.activate_state_not, name='activate_state_not'),
    # 普通班
    path('regular_class/',admin_view.regular_class, name='regular_class'),
    # 学生修改
    path('student_mod/', admin_view.student_mod, name='student_mod'),
    path('student_mod_check/', admin_view.student_mod_check, name='student_mod_check'),

    # 补贴
    path('subsidy/', admin_view.subsidy, name='subsidy'),
    path('subsidy_add/', admin_view.subsidy_add, name='subsidy_add'),
    path('subsidy_mod/', admin_view.subsidy_mod, name='subsidy_mod'),
    path('subsidy_add_check/', admin_view.subsidy_add_check, name='subsidy_add_check'),
    path('subsidy_mod_check/', admin_view.subsidy_mod_check, name='subsidy_mod_check'),
    # 住宿费
    path('dormitory/', admin_view.dormitory, name='dormitory'),
    # path('dormitory_add/', admin_view.dormitory_add, name='dormitory_add'),
    # 住宿费记录
    path('dormitory_record/', admin_view.dormitory_record, name='dormitory_record'),
    # 交易结算
    path('dormitory_close', admin_view.dormitory_close, name='dormitory_close'),
    # 财务删除
    path('remove_subsidy/', admin_view.remove_subsidy, name='remove_subsidy')
]

qyedu/account/models.py
from django.db import models
from django.contrib.auth.models import User


class UserRole(models.Model):
    """
    用户角色表。
    """
    role_name = models.CharField(max_length=20)

    def __str__(self):
        return self.role_name


class NewUser(models.Model):
    """
    用户资料表
    """
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    realname = models.CharField(max_length=15)
    role = models.ForeignKey(UserRole, on_delete=models.DO_NOTHING)
    mobile_number = models.CharField(max_length=15)
    id_card = models.CharField(max_length=25)
    birthday = models.DateField(null=True, blank=True)
    info = models.TextField()
    choice = (
        (0,'女'),
        (1,'男'),
    )
    gender = models.PositiveSmallIntegerField(choices=choice, default=1)
    edu_level = models.CharField(max_length=100)
    home_address = models.CharField(max_length=100)
    choice_s = (
        (0,'未激活'),
        (1,'已激活'),
        (2,'结业'),
        (3,'退学')
    )
    state = models.PositiveSmallIntegerField(choices=choice_s, default=0)
    choice_is = (
        (0,'否'),
        (1,'是'),
    )
    is_goodman = models.PositiveSmallIntegerField(choices=choice_is, default=0)
    choice_del = (
        (0,'正常'),
        (1,'删除'),
    )
    is_del = models.PositiveSmallIntegerField(choices=choice_del, default=0)
    choice_pay = (
        (0, '未设定'),
        (1, '贷款缴费'),
        (2, '现金缴费')
    )
    pay_mode = models.PositiveSmallIntegerField(choices=choice_pay, default=0)

    def __str__(self):
        return self.realname

qyedu/six_group/models.py
"""
训练营模块:新生分配训练营
"""
from django.db import models

# from account.models import NewUser
#
#
# class Subsidy(models.Model):
#     money = models.IntegerField()
#     type_chose = ((1, '补贴'), (2, '住宿费'))
#     type = models.PositiveSmallIntegerField(default=1, choices=type_chose)
#     data_time = models.DateTimeField(auto_now_add=True)
#     pay_time = models.DateField()
#     student = models.ForeignKey(NewUser, on_delete=models.CASCADE, related_name='subsidys')
#     keyboarder = models.ForeignKey(NewUser, on_delete=models.CASCADE, related_name='subsidyes')


qyedu/six_group/templates/six_group/six_dormitory.html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    {% load static %}
    <!--[if lt IE 9]>
<script type="text/javascript" src="/static/lib/html5shiv.js"></script>
<script type="text/javascript" src="/staticlib/respond.min.js"></script>
<![endif]-->
    <link rel="stylesheet" type="text/css" href="/static/h-ui/css/H-ui.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/h-ui.admin/css/H-ui.admin.css" />
    <link rel="stylesheet" type="text/css" href="/static/lib/Hui-iconfont/1.0.8/iconfont.css" />
    <link rel="stylesheet" type="text/css" href="/static/h-ui.admin/skin/default/skin.css" id="skin" />
    <link rel="stylesheet" type="text/css" href="/static/h-ui.admin/css/style.css" />
    <!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
    <title>用户管理</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 财务管理 <span class="c-gray en">&gt;</span> 宿舍费用 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="page-container">
    <form action="{% url 'six_group:dormitory' %}" method="post">
        {% csrf_token %}
        <div class="text-c">
            <input type="text" class="input-text" style="width:250px" value="{{ realname }}"  placeholder="输入学生姓名" id="" name="realname">
            <button type="submit" class="btn btn-success radius" id="" name=""><i class="Hui-iconfont">&#xe665;</i> 搜用户</button>
        </div>
        <div class="cl pd-5 bg-1 bk-gray mt-20"> <span class="l">
    </span> <span class="r">共有数据：<strong>{{ subsidy.count }}</strong> 条</span>
            <a href="{% url 'six_group:dormitory_record' %}?a_id=2" class="btn btn-primary radius">交易记录</a>
        </div>
    </form>
    <div class="mt-20">
        <table class="table table-border table-bordered table-hover table-bg table-sort">
            <thead>
            <tr class="text-c">
                <th width="25"><input type="checkbox" name="" value=""></th>
{#                <th width="60">ID</th>#}
                <th width="60">姓名</th>
                <th width="40">性别</th>
                <th width="90">手机</th>
                <th width="90">宿舍费(元)</th>
                <th width="120">班级</th>
                <th width="40">录入人</th>
                <th width="40">录入时间</th>
                <th width="40">计划缴费时间</th>
                <th width="40">结算状态</th>
                <th width="100">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for s in subsidy %}
                <tr class="text-c">
                    <td><input type="checkbox" value="1" name=""></td>
{#                    <td>{{ s.student.id }}</td>#}
                    <td>{{ s.student.realname }}</td>
                    <td>{{ s.student.get_gender_display }}</td>
                    <td>{{ s.student.mobile_number }}</td>
                    <td>{{ s.money }}</td>
                    <td>{{ s.student.stuclass_student.first.grade }}</td>
                    <td>{{ s.keyboarder }}</td>
                    <td>{{ s.data_time|date:'Y-m-d' }}</td>
                    <td>{{ s.pay_time|date:'Y-m-d' }}</td>
                    <td>{{ s.get_state_display }}</td>
                    <td class="td-manage">
                        <button style="width: 40px" onclick="dormitory_close(this,'{{ s.id }}')">结算</button>
                        <a title="编辑"  href="javascript:;" onclick="member_edit('栏目编辑','{% url 'six_group:subsidy_mod'%}?s_id={{ s.id }}', '4','','510')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>  <a title="删除" href="javascript:;" a="{{ u.id }}" id="a" onclick="member_del(this,'{{ s.id }}')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="/static/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/lib/layer/2.4/layer.js"></script>
<script type="text/javascript" src="/static/h-ui/js/H-ui.min.js"></script>
<script type="text/javascript" src="/static/h-ui.admin/js/H-ui.admin.js"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="/static/lib/My97DatePicker/4.8/WdatePicker.js"></script>
<script type="text/javascript" src="/static/lib/datatables/1.10.0/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/static/lib/laypage/1.2/laypage.js"></script>
<script type="text/javascript">
    $(function(){
        $('.table-sort').dataTable({
            "aaSorting": [[ 1, "desc" ]],//默认第几个排序
            "bStateSave": true,//状态保存
            "aoColumnDefs": [
                //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
                {"orderable":false,"aTargets":[0,7,8]}// 制定列不参与排序
            ]
        });

    });
    /*用户-添加*/
    function member_add(title,url,w,h){
        layer_show(title,url,w,h);
    }
    /*用户-查看*/
    function member_show(title,url,id,w,h){
        layer_show(title,url,w,h);
    }
    /*用户-编辑*/
    function member_edit(title,url,id,w,h){
        layer_show(title,url,w,h);
    }
    /*密码-修改*/
    function change_password(title,url,id,w,h){
        layer_show(title,url,w,h);
    }
    /*财务-删除*/
    function member_del(obj,id){
        layer.confirm('确认要删除吗？',function(index){
            $.ajax({
                type: 'get',
                url: '{% url 'six_group:remove_subsidy' %}?s_id=' + id,
                success: function(data){
                    if (data.status == 1) {
                        $(obj).parents("tr").remove();
                        layer.msg(data.msg,{icon:1,time:1000});
                    } else {
                        layer.msg(data.msg,{icon:1,time:1000});
                    }

                },
                error:function(data) {
                    console.log(data.msg);
                },
            });
        });
    }
    // 财务结算
    function dormitory_close(obj,id){
        layer.confirm('是否结算？',function(index){
            $.ajax({
                type: 'get',
                url: '{% url 'six_group:dormitory_close' %}',
                data: {'s_id': id},
                success: function(data){
                    $(obj).parents("tr").remove();
                    layer.msg('结算成功!',{icon:1,time:1000});
                },
                error:function(data) {
                    console.log(data.msg);
                },
            });
        });
    }
</script>
</body>
</html>

qyedu/six_group/templates/six_group/six_train_class.html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "h-ui/css/H-ui.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/H-ui.admin.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "lib/Hui-iconfont/1.0.8/iconfont.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/skin/default/skin.css" %}" id="skin" />
    <link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/style.css" %}" />
    <title>训练营管理</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 班级管理 <span class="c-gray en">&gt;</span> 训练营 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="page-container">
    <form action="{% url 'six_group:training_camp' %}" method="post" >
        {% csrf_token %}
        <div class="text-c">
            <button onclick="removeIframe()" class="btn btn-primary radius">关闭选项卡</button>
            {#        日期范围：#}
            {#		<input type="text" onfocus="WdatePicker({ maxDate:'#F{$dp.$D(\'logmax\')||\'%y-%M-%d\'}' })" id="logmin" class="input-text Wdate" style="width:120px;">#}
            {#		-#}
            {#		<input type="text" onfocus="WdatePicker({ minDate:'#F{$dp.$D(\'logmin\')}',maxDate:'%y-%M-%d' })" id="logmax" class="input-text Wdate" style="width:120px;">#}
            <input type="text" name="realname" id="" placeholder=" 学员名称" style="width:250px" class="input-text" value="{{ realname }}">
            <button name="" id="btnsubmit" class="btn btn-success" type="submit"><i class="Hui-iconfont">&#xe665;</i> 搜索学员信息</button>
        </div>
    </form>
    <div class="mt-20">
        <table class="table table-border table-bordered table-bg table-hover table-sort table-responsive">
            <thead>
            <tr class="text-c">
                <th width="25"><input type="checkbox" name="" value=""></th>
                <th width="40">ID</th>
                <th width="50">学员姓名</th>
                <th width="60">手机号</th>
                <th width="90">身份证</th>
                <th width="50">出生日期</th>
                <th width="50">性别</th>
                <th width="50">学历</th>
                <th width="140">家庭住址</th>
                <th width="50">学员状态</th>
                <th width="50">班级名称</th>
                <th width="50">是否激活</th>
                <th width="60">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for stu in stu_class %}
                {% if stu.student.role.role_name == '学员' and stu.student.is_del == 0 %}
                    <tr class="text-c">
                        <td><input type="checkbox" value="{{ stu.student.id }}" name=""></td>
                        <td>{{ stu.student.id }}</td>
                        <td>{{ stu.student.realname }}</td>
                        <td>{{ stu.student.mobile_number }}</td>
                        <td>{{ stu.student.id_card }}</td>
                        <td>{{ stu.student.birthday|date:"Y-m-d" }}</td>
                        <td>{{ stu.student.get_gender_display }}</td>
                        <td>{{ stu.student.edu_level }}</td>
                        <td>{{ stu.student.home_address }}</td>
                        <td>{{ stu.student.get_state_display }}</td>
                        <td>{{ stu.grade }}</td>
                        <td>
                            <a title="编辑" href="javascript:;" onclick="system_category_edit('学员编辑','{% url 'six_group:activate_state' %}?n_id={{ stu.student.id }}','1','400','300')" style="text-decoration:none"><button style="width: 20px" class="Hui-iconfont">是</button></a>
                            <button onclick="system_category_not(this,'{{ stu.student.id }}')" style="width: 20px" class="Hui-iconfont">否</button>
                        </td>
                        <td class="f-14">
                            <a title="编辑" href="javascript:;" onclick="system_category_edit('财务编辑','{% url 'six_group:subsidy_add' %}?n_id={{ stu.student.id }}','1','750','650')" style="text-decoration:none"><i class="Hui-iconfont">财务 </i></a>
                            <a title="编辑" href="javascript:;" onclick="system_category_edit('学员编辑','{% url 'new_admin:student_amend' %}?n_id={{ stu.student.id }}','1','750','650')" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>
                            <a style="text-decoration:none; display: none;" class="ml-5" onclick="system_category_del(this,'{{ stu.student.id }}')" href="javascript:;" title="删除"><i class="Hui-iconfont">&#xe6e2;</i></a>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static "lib/jquery/1.9.1/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "lib/layer/2.4/layer.js" %}"></script>
<script type="text/javascript" src="{% static "h-ui/js/H-ui.min.js" %}"></script>
<script type="text/javascript" src="{% static "h-ui.admin/js/H-ui.admin.js" %}"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="{% static "lib/My97DatePicker/4.8/WdatePicker.js" %}"></script>
<script type="text/javascript" src="{% static "lib/datatables/1.10.0/jquery.dataTables.min.js" %}"></script>
<script type="text/javascript" src="{% static "lib/laypage/1.2/laypage.js" %}"></script>
<script type="text/javascript">
    {% if messages %}
        {% for message in messages %}
            $.Huimodalalert('{{ message }}',2000);
        {% endfor %}
    {% endif %}
    $('.table-sort').dataTable({
        "aaSorting": [[ 1, "desc" ]],//默认第几个排序
        "bStateSave": true,//状态保存
        "pading":false,
        "aoColumnDefs": [
            //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
            {"orderable":false,"aTargets":[0,8]}// 不参与排序的列
        ]
    });
    function system_category_edit(title,url,id,w,h){
       a = {{ user.role.id }};
       if (title == "财务编辑" && a != 7){
           $.Huimodalalert('权限不足',2000);
       }
       else{
           layer_show(title,url,w,h);
       }
       return false
    }
    /*资讯-添加*/
    function article_add(title,url,w,h){
        var index = layer.open({
            type: 2,
            title: title,
            content: url
        });
        layer.full(index);
    }
    /*资讯-编辑*/
    function article_edit(title,url,id,w,h){
        var index = layer.open({
            type: 2,
            title: title,
            content: url
        });
        layer.full(index);
    }
    function system_category_del(obj,id){
        layer.confirm('确认要删除吗？',function(index){
            $.ajax({
                type: 'GET',
                url: '{% url "new_admin:student_delete"%}?n_id=' + id,
                dataType: 'json',
                success: function(data){
                    if (data.status == 1){
                        $(obj).parents("tr").remove();
                        layer.msg(data.msg,{icon:1,time:1000});
                        {#function (){#}
                        {#    location.reload();#}
                        //});
                    }else {
                        layer.msg(data.msg,{icon:6,time:1000});
                    }
                },
            });
        });
    }
    function system_category_not(obj,id){
        layer.confirm('确认要放弃学习吗？',function(index){
            $.ajax({
                type: 'GET',
                url: '{% url "six_group:activate_state_not"%}?n_id=' + id,
                dataType: 'json',
                success: function(data){
                    if (data.status == 1){
                        $(obj).parents("tr").remove();
                        layer.msg(data.msg,{icon:1,time:1000});
                        {#function (){#}
                        {#    location.reload();#}
                        //});
                    }else {
                        layer.msg(data.msg,{icon:6,time:1000});
                    }
                },
            });
        });
    }

</script>
</body>
</html>