qyedu/evaluate/urls.py
from django.urls import path
from . import views as evaluate_view


app_name = 'evaluate'
# 考试信息
urlpatterns = [
    # 进入录入考试的页面
    path('evaluate_test/add', evaluate_view.evaluate_test_add, name='evaluate_test_add'),
    # 添加哪场考试
    path('evaluate_test/add/check', evaluate_view.evaluate_test_add_check, name='evaluate_test_add_check'),
    # 展示考试信息页面
    path('evaluate_test/show/', evaluate_view.evaluate_test_show, name='evaluate_test_show'),
    # 修改考试信息
    path('evaluate_test/modify/', evaluate_view.evaluate_test_modify, name='evaluate_test_modify'),
    path('evaluate_test/modify/check/', evaluate_view.evaluate_test_modify_check, name='evaluate_test_modify_check'),
    # 删除考试信息
    path('evaluate_test/delete/', evaluate_view.evaluate_test_delete, name='evaluate_test_delete')

]

# 题库
urlpatterns += [
    # 录入考题页面
    path('evaluate_test/question/', evaluate_view.evaluate_test_question, name='evaluate_test_question'),
    # 添加考题
    path('evaluate_test/question/add/', evaluate_view.evaluate_test_question_add, name='evaluate_test_question_add'),
    path('evaluate_test/question/add/check/', evaluate_view.evaluate_test_question_add_check, name='evaluate_test_question_add_check'),
    # 修改考题
    path('evaluate_test/question/modify/', evaluate_view.evaluate_test_question_modify, name='evaluate_test_question_modify'),
    path('evaluate_test/question/modify/check', evaluate_view.evaluate_test_question_modify_check, name='evaluate_test_question_modify_check'),
    # 删除考题
    path('evaluate_test/question/delete/', evaluate_view.evaluate_question_delete, name='evaluate_question_delete'),
]

# 答案库
urlpatterns += [

    # 录入答案页面
    path('evaluate_test/answer/', evaluate_view.evaluate_test_answer, name='evaluate_test_answer'),
    # 添加答案页面
    path('evaluate_test/answer/add/', evaluate_view.evaluate_test_answer_add, name='evaluate_test_answer_add'),
    # 添加答案
    path('evaluate_test/answer/add/check/', evaluate_view.evaluate_test_answer_add_check, name='evaluate_test_answer_add_check'),


    # 修改答案页面
    path('evaluate_test/answer/modify/', evaluate_view.evaluate_test_answer_modify, name='evaluate_test_answer_modify'),
    # 修改答案
    path('evaluate_test/answer/modify/check/', evaluate_view.evaluate_test_answer_modify_check, name='evaluate_test_answer_modify_check'),

    # 删除答案
    path('evaluate_test/answer/delete/', evaluate_view.evaluate_test_answer_delete, name='evaluate_test_answer_delete'),

]

# 职业素养课考试
urlpatterns += [
    path('evaluate_course_test/show/', evaluate_view.evaluate_course_test_show, name="evaluate_course_test_show"),
    path('evaluate_course_test/submit/', evaluate_view.evaluate_course_test_submit, name='evaluate_course_test_submit'),
    path('evaluate_course_test_answer/', evaluate_view.evaluate_course_test_answer, name='evaluate_course_test_answer'),
]

# 讲师评测
urlpatterns += [
    # 展示考题
    path('evaluate_teacher_test/', evaluate_view.evaluate_teacher_test, name='evaluate_teacher_test'),
    # 提交考题
    path('evaluate_teacher_test/submit/', evaluate_view.evaluate_teacher_test_submit, name='evaluate_teacher_test_submit'),
    # 考试答案,及批阅
    path('evaluate_student_answer/', evaluate_view.evaluate_student_answer, name='evaluate_student_answer')
]

# 班主任评测
urlpatterns += [
    # 展示考题
    path('evaluate_headteacher_test/', evaluate_view.evaluate_headteacher_test, name='evaluate_headteacher_test'),
    # 提交考题
    path('evaluate_headteacher_test/submit/', evaluate_view.evaluate_headteacher_test_submit, name='evaluate_headteacher_test_submit'),
    # 考试答案, 及批阅
    path('evaluate_headteacher_test/answer/', evaluate_view.evaluate_headteacher_test_answer, name='evaluate_headteacher_test_answer'),
    # ajax-获取总成绩并保存
    path('evaluate_headteacher_test/sum/', evaluate_view.evaluate_headteacher_test_sum, name='evaluate_headteacher_test_sum'),


]


# 后勤服务评测
urlpatterns += [
    # 展示考题
    path('evaluate_service_test/', evaluate_view.evaluate_service_test, name='evaluate_service_test'),
    # 提交考题
    path('evaluate_service_test/submit/', evaluate_view.evaluate_service_test_submit, name='evaluate_service_test_submit'),
    # 考试答案
    path('evaluate_service_test/answer/', evaluate_view.evaluate_service_test_answer, name='evaluate_service_test_answer'),
]


qyedu/qyedu/urls.py
# coding=utf8
# from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    # 授课
    path('give_lessons/', include('give_lessons.urls')),
    # 后台
    path('new_admin/', include('new_admin.urls')),
    # 学习
    path('study/', include('study.urls')),
    # 人才库
    path('talent_all/', include('talent_all.urls')),
    # path('admin/', admin.site.urls),
    # 宿舍
    path('dormitory/', include("dormitory.urls")),
    # 考试
    path('examination/', include("examination.urls")),
    # 第三方模块验证码相关
    path('captcha/', include('captcha.urls')),
    # 招生
    path('recruit_students/', include('recruit_students.urls')),
    # 就业
    path('job/', include('obtain_employment.urls')),
    # 训练营
    path('star/', include('six_group.urls')),
    # 访谈
    path('interview/', include('interview.urls')),
    # 评测
    path('evaluate/', include('evaluate.urls')),

]


urlpatterns += [
    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='media')
]

qyedu/evaluate/models.py
"""
测评、职业素养
"""
from django.db import models
from new_admin.models import *


# Create your models here.
class ReviewTest(models.Model):
    """
    考试记录表(考试对象是学生)
    """
    # 学生所在班级
    class_grade = models.ForeignKey(ClassGrade,on_delete=models.CASCADE, related_name='rt_class_grade')
    # 评测对象--老师/职业素养课--老师
    teacher_name = models.ForeignKey(NewUser, models.DO_NOTHING, related_name='rt_teacher_name')
    # 本次测试名称
    test_name = models.CharField(max_length=15)
    # 测试时间
    review_test_date = models.DateTimeField()
    # 是否允许考试(默认为0)
    can_test = models.BooleanField(default=0)

    def __str__(self):
        return self.test_name


class TestQuestion(models.Model):
    """
    问题库(测试问题表)
    """
    # 外键 -- 评测表
    review_test = models.ForeignKey(ReviewTest, on_delete=models.DO_NOTHING,related_name='tq_review_test')
    test_categoty_choices = (
        (1, '讲师评测'),
        (2, '班主任评测'),
        (3, '后勤评测'),
        (4, '职业素养测评'),
    )
    # 测试--类型
    test_category = models.SmallIntegerField(choices=test_categoty_choices, default=1)
    test_question_categoty_choices = (
        (1, '单选题'),
        (2, '是非题'),
        (3, '主观题')
    )
    # 测试题目类型
    test_question_category = models.SmallIntegerField(choices=test_question_categoty_choices, default=1)
    # 最大分数(主要针对主观题, 默认10分)
    max_score = models.IntegerField(default=10)
    # 测试题目内容
    test_question_content = models.CharField(max_length=200)

    def __str__(self):
        return self.test_question_content


class Answer(models.Model):
    """
    答案库(问题答案表)
    """
    # 外键--问题
    question = models.ForeignKey(TestQuestion, on_delete=models.CASCADE, related_name='a_question')
    # 答案内容
    answer_content = models.CharField(max_length=500)
    # 每个答案所对应的分数
    answer_score = models.IntegerField(default=0)

    def __str__(self):
        return self.answer_content


class StudentAnswer(models.Model):
    """
    学生答案表
    """
    # 考试记录
    review_test = models.ForeignKey(ReviewTest, on_delete=models.DO_NOTHING, related_name='sa_review_test')
    # 试卷问题
    question = models.ForeignKey(TestQuestion, on_delete=models.CASCADE, related_name='sa_question')
    # 答案(选择题为选项, 简答题为内容)
    answer = models.CharField(max_length=500)
    # 考试人
    student = models.ForeignKey(NewUser, on_delete=models.CASCADE, related_name='sa_student')
    # 交卷时间
    submit_time = models.DateTimeField(auto_now_add=True)


class ReviewResult(models.Model):
    """
    测评结果--成绩表
    """
    # 测试名称
    review_test = models.ForeignKey(ReviewTest, on_delete=models.DO_NOTHING, related_name='r_review_test')
    # 测试人
    student = models.ForeignKey(NewUser, on_delete=models.CASCADE, related_name='r_student')

    # 测试类型
    test_category = models.CharField(max_length=20)
    # 测试总分数(缺考为-1)
    review_test_score = models.IntegerField(default=-1)


# 职业素养课表
class Course(models.Model):
    name = models.CharField(max_length=20)
    outline = models.TextField(max_length=300)
    demand = models.TextField(max_length=300)
    open_time = models.DateTimeField()
    add_time = models.DateTimeField(auto_now_add=True)

qyedu/evaluate/forms.py
from django import forms

from evaluate.models import Answer


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['answer_content', 'answer_score', 'question']
        widgets = {
            'answer_content': forms.TextInput(attrs={'id': "answer_content", 'name': "answer_content", 'class': "input-text",}),
            'answer_score': forms.TextInput(attrs={'id': "answer_score", 'name': "answer_score", 'class': "input-text", 'placeholder': '输入答案内容'}),
            'question': forms.Select(attrs={'id':'question', 'name':'question', 'class': 'select'})
        }

qyedu/evaluate/templates/evaluate/course_test_answer.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        <ul>
            <h2>{{ answer_list1.review_test.test_name }}---{{ answer_list1.question.get_test_category_display }}</h2>
            <span>姓名: {{ student.realname }}</span>
            {% for s_answer in answer_list %}
                <li>
                    <h4>{{ s_answer.question.test_question_content }}({{ s_answer.question.max_score }})</h4>
                    <span>{{ s_answer.answer }}</span>
                    {% for answer in s_answer.question.a_question.all %}
                        {% if answer.answer_content == s_answer.answer %}
                            ({{ answer.answer_score }})
                        {% endif %}
                    {% endfor %}
                </li>
            {% endfor %}
        </ul>
        <p>总分:{{ sum_score }}(未计入主观题分数)</p>
    </body>
</html>

qyedu/evaluate/templates/evaluate/ht_student_answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        li {
            list-style: none;
        }
    </style>
</head>
<body>
<ul>
    <li>
        <h2>{{ student_answer1.review_test.test_name }}</h2>
        <span>{{ student_answer1.question.get_test_category_display }}</span>
        {% for answer in student_answer %}
            <ul>
                <h4>{{ answer.question }} 最高分:({{  answer.question.max_score }})</h4>
                <li>
                    {% if answer.question.get_test_question_category_display == 3%}
                        <textarea name="" id="" cols="30" rows="10">
                        {{ answer.answer }}
                        </textarea>
                    {% else %}
                        <span>{{ answer.answer }}</span>
                    {% endif %}
                    {% for answer1 in answer.question.a_question.all %}
                        {% if answer1.answer_content == answer.answer %}
                            ({{ answer1.answer_score }})
                        {% endif %}
                    {% endfor %}
                </li>
            </ul>
        {% endfor %}
    </li>
</ul>
<span>非主观题 : {{ sum_score }}</span> + (主观题分数) :<input type="text" class="sum">
<br>
<span>总分: </span> <span class="sum">____</span>  <button>提交</button>

</body>
</html>
<script src="{% static 'js/jquery.min.js' %}"></script>

<script>
    $('button').click(function () {
        sum = $('.sum').val();
        var test_name = '{{ student_answer1.review_test.test_name }}';
        var test_category = '{{ student_answer1.question.get_test_category_display }}';
        sum = parseInt(sum) + parseInt({{ sum_score }});
        $.ajax({
            url : '{% url 'evaluate:evaluate_headteacher_test_sum' %}',
            data: {'sum':sum, 's_id': {{ student_answer1.student.id }}, 'test_name': test_name, 'test_category': test_category},
            success: function(data) {
                console.log(data.data);
                $('.sum').text(data.data);
            }
        })
    })
</script>

qyedu/evaluate/templates/evaluate/service_test_answer.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        <ul>
            <h2>{{ answer_list1.question.get_test_category_display }}----{{ answer_list1.review_test.test_name }}</h2>
            <span>{{ student.realname }}</span>
            {% for s_answer in answer_list %}
            <li>
                <h4>{{ s_answer.question.test_question_content }}({{ s_answer.question.max_score }})</h4>
                <span>{{ s_answer.answer }}</span>
                {% for answer in s_answer.question.a_question.all %}
                    {% if answer.answer_content == s_answer.answer %}
                        ({{ answer.answer_score}})
                    {% endif %}
                {% endfor %}
            </li>
            {% endfor %}
        </ul>
        <p>总分:{{ sum_score }}(未计入主观题分数)</p>
    </body>
</html>

qyedu/evaluate/templates/evaluate/service_test_show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <style>
            li{
                list-style: decimal;
            }
        </style>
    </head>
    <body>
        <form action="{% url 'evaluate:evaluate_service_test_submit' %}" method="post">
            {% csrf_token %}
            <ul>
                <h2>{{ question_list.get_test_category_display }}----{{ question_list.review_test.test_name }}</h2>
                {% for type in type_list1 %}
                    <li>
                        <h4>{{ type.test_question_content }}</h4>
                        {% for answer in type.a_question.all %}
                            <input type="radio" value="{{ answer }}" id="answer{{ answer.id }}" name="answer_{{ type.id }}">
                            <label for="answer{{ answer.id }}">{{ answer }}</label>
                        {% endfor %}
                    </li>
                {% endfor %}
                {% for type in type_list2 %}
                    <li>
                        <h4>{{ type.test_question_content }}</h4>
                        {% for answer in type.a_question.all %}
                            <input type="radio" value="{{ answer }}" id="answer{{ answer.id }}" name="answer_{{ type.id }}">
                            <label for="answer{{ answer.id }}">{{ answer }}</label>
                        {% endfor %}
                    </li>
                {% endfor %}
                {% for type in type_list3 %}
                    <li>
                        <h4>{{ type.test_question_content }}</h4>
                        {% for answer in type.a_question.all %}
                            <textarea name="answer_{{ type.id }}" id="" cols="30" rows="10"></textarea>
                        {% endfor %}
                    </li>
                {% endfor %}
            </ul>
            <input type="submit" value="提交">
        </form>
    </body>
</html>

qyedu/evaluate/templates/evaluate/show_all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

qyedu/evaluate/templates/evaluate/student_answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        <h2>{{ student_answer1.review_test.test_name }}</h2>
        <span>{{ student_answer1.question.get_test_category_display }}</span>
        <span>姓名 : {{ student.realname }}</span>
        {% for s_answer in student_answer %}
            <li>
            p656467
                <h4>{{ s_answer.question.test_question_content }}({{  s_answer.question.max_score }})</h4>
{#                <span>{{ s_answer.answer }}</span>#}
                {% if s_answer.question.get_test_question_category_display == 3%}
                    <textarea name="" id="" cols="30" rows="10">
                    {{ s_answer.answer }}
                    </textarea>
                {% else %}
                    <span>{{ s_answer.answer }}</span>
                {% endif %}
                {% for answer in s_answer.question.a_question.all %}
                    {% if answer.answer_content == s_answer.answer %}
                        ({{ answer.answer_score }})
                    {% endif %}
                {% endfor %}
            </li>
        {% endfor %}
    </ul>
    <p>总分{{ sum_score }}(未计入主观题分数)</p>
</body>
</html>

qyedu/evaluate/templates/evaluate/teacher_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        li{
            list-style: decimal;
        }
    </style>
</head>
<body>
<form action="{% url 'evaluate:evaluate_teacher_test_submit' %}" method="post">
    {% csrf_token %}
    <ul>
        <h2>{{ teacher_test1.review_test.test_name }}</h2>
        <span>{{ teacher_test1.get_test_category_display }}</span>
        {% for test in teacher_test %}
            <li>
                <h4>{{ test.test_question_content }}</h4>
                {% for content in test.a_question.all %}
                    <input type="radio" value="{{ content.answer_content }}" id="content{{ content.id }}" name="content_{{ test.id }}">
                    <label for="content{{ content.id }}">{{ content.answer_content }}</label>
                {% endfor %}
            </li>
        {% endfor %}
        {% for test in teacher_test2 %}
            <li>
                <h4>{{ test.test_question_content }}</h4>
                {% for content  in test.a_question.all %}
                    <input type="radio" value="{{ content.answer_content }}" id="content{{ content.id }}" name="content_{{ test.id }}">
                    <label for="content{{ content.id }}">{{ content.answer_content }}</label>
                {% endfor %}
            </li>
        {% endfor %}
        {% for test in teacher_test3 %}
            <li>
                <h4>{{ test.test_question_content }}</h4>
                {% for content in test.a_question.all %}
                    <p>{{ content.answer_content }}</p>
                    <textarea name="content_{{ test.id }}" id="" cols="100" rows="5"></textarea>
                {% endfor %}
            </li>
        {% endfor %}
    </ul>
    <input type="submit" value="提交">
</form>

</body>
</html>

qyedu/evaluate/templates/evaluate/test_question.html
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css" href="{% static "h-ui/css/H-ui.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/H-ui.admin.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "lib/Hui-iconfont/1.0.8/iconfont.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/skin/default/skin.css" %}" id="skin" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/style.css" %}" />
<link rel="stylesheet" href="{% static 'new_admin/css/new_admin.css' %}">
<!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<title>问题页面</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页
	<span class="c-gray en">&gt;</span>
	职业素养课管理
	<span class="c-gray en">&gt;</span>
	问题页面
	<a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a>
</nav>
<div class="page-container">
	<div class="text-c">
		<input type="text" name="" id="" placeholder="栏目名称、id" style="width:250px" class="input-text">
		<button name="" id="" class="btn btn-success" type="submit"><i class="Hui-iconfont">&#xe665;</i> 搜索</button>
	</div>
	<div class="cl pd-5 bg-1 bk-gray mt-20">
		<span class="l">
		<a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a>
		<a class="btn btn-primary radius" href="{% url 'evaluate:evaluate_test_question_add' %}"><i class="Hui-iconfont">&#xe600;</i> 添加题目</a>
		</span>
		<span class="r">共有数据：<strong>{{ question_list.count }}</strong> 条</span>
	</div>
	<div class="mt-20">
		<table class="table table-border table-bordered table-hover table-bg table-sort">
			<thead>
				<tr class="text-c">
					<th width="40">ID</th>
                    <th width="50">测试名称</th>
                    <th width="40">测试类型</th>
                    <th width="20">题目类型</th>
                    <th width="300">题目内容</th>
                    <th width="50">最高分数</th>
                    <th width="50">操作</th>
				</tr>
			</thead>
			<tbody>
				{% for test in question_list %}
                <tr class="text-c">
                    <td>{{ test.id }}</td>
                    <td>{{ test.review_test.test_name }}</td>
                    <td>{{ test.get_test_category_display }}</td>
                    <td>{{ test.get_test_question_category_display }}</td>
                    <td>{{ test.test_question_content }}</td>
                    <td>{{ test.max_score }}</td>
                    <td class="td-manage"> <a title="编辑" href="{% url 'evaluate:evaluate_test_question_modify' %}?test_id={{ test.id }}" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a> <a title="删除" onclick="evaluate_question_del(this,'{{ test.id }}')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a></td>
                </tr>
                {% empty %}
                <tr class="odd"><td colspan="6" class="dataTables_empty">没有数据</td></tr>
            {% endfor %}
			</tbody>
		</table>
	</div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static "lib/jquery/1.9.1/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "lib/layer/2.4/layer.js" %}"></script>
<script type="text/javascript" src="{% static "h-ui/js/H-ui.min.js" %}"></script>
<script type="text/javascript" src="{% static "h-ui.admin/js/H-ui.admin.js" %}"></script>

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="{% static "lib/My97DatePicker/4.8/WdatePicker.js" %}"></script>
<script type="text/javascript" src="{% static "lib/datatables/1.10.0/jquery.dataTables.min.js" %}"></script>
<script type="text/javascript" src="{% static "lib/laypage/1.2/laypage.js" %}"></script>
<script type="text/javascript">
    {% if messages %}
        {% for message in messages %}
            alert('{{ message }}');
        {% endfor %}
    {% endif %}

$('.table-sort').dataTable({
	"aaSorting": [[ 1, "desc" ]],//默认第几个排序
	"bStateSave": true,//状态保存
	"aoColumnDefs": [
	  //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
	  {"orderable":false,"aTargets":[0,4]}// 制定列不参与排序
	]
});
/*系统-栏目-添加*/
function system_category_add(title,url,w,h){
	layer_show(title,url,w,h);
}
/*系统-栏目-编辑*/
function system_category_edit(title,url,id,w,h){
	layer_show(title,url,w,h);
}
/*系统-栏目-删除*/
function evaluate_question_del(obj,id){
	layer.confirm('确认要删除吗？',function(index){
		$.ajax({
			type: 'GET',
			url: '{% url 'evaluate:evaluate_question_delete' %}?test_id='+id,
			dataType: 'json',
			success: function(data){
			    console.log(data.status);
			    if (data.status == 1){
			        console.log(data.status);
                       $(obj).parents("tr").remove();
				        layer.msg('已删除!',{icon:1,time:1000});
                    }else {
                        layer.msg("删除失败!!!",{icon:6,time:1000});
                    }
			},
            error:function(data) {
                console.log(data.status);
                },
		});
	});
}
</script>
</body>
</html>