qyedu/new_admin/urls.py
# coding=utf-8
from django.urls import path
from . import views as admin_view
from django.views.decorators.cache import cache_page
app_name = 'new_admin'

# 登录相关
urlpatterns = [
    # 首页
    path('', admin_view.index, name='index'),
    # 登录
    path('login/', admin_view.login, name='login'),
    # 登录验证
    path('login_check/', admin_view.login_check, name='login_check'),
    # 欢迎页
    path('welcome/', admin_view.welcome, name='welcome'),
    # 退出登录
    path('logout_view/', admin_view.logout_view, name='logout_view'),
]

# 菜单
urlpatterns += [
    # 栏目列表
    path('category/', admin_view.category, name='category'),
    # 栏目添加
    path('category/add/', admin_view.category_add, name='category_add'),
    # 栏目添加验证
    path('category/add/check/', admin_view.category_add_check, name='category_add_check'),
    # 删除栏目
    path('category/del/', admin_view.category_del, name='category_del'),
    # 修改栏目
    path('category/category_modify/', admin_view.category_modify, name='category_modify'),
    # 修改栏目验证
    path('category/category_modify/check/', admin_view.category_modify_check, name='category_modify_check'),
]

# 宿舍
urlpatterns += [
    # 宿舍列表
    path('dorm/', admin_view.dorm, name='dorm'),
    # 宿舍添加
    path('dorm/add/', admin_view.dorm_add, name='dorm_add'),
    # 宿舍添加验证
    path('dorm/add/check', admin_view.dorm_add_check, name='dorm_add_check'),
    # 宿舍修改
    path('dorm/modify/', admin_view.dorm_modify, name='dorm_modify'),
    # 宿舍修改验证
    path('dorm/modify/check', admin_view.dorm_modify_check, name='dorm_modify_check'),
    # 宿舍删除
    path('dorm/del/', admin_view.dorm_del, name='dorm_del'),
]

# 管理员管理
urlpatterns += [
    # 管理员列表
    path('admin/', admin_view.admin, name='admin'),
    # 管理员添加
    path('admin/add/check/', admin_view.admin_add_check, name='admin_add_check'),
    # 管理员添加验证
    path('admin/add/', admin_view.admin_add, name='admin_add'),
    # 删除管理员
    path('admin/del/', admin_view.admin_del, name='admin_del'),
    # 修改管理员
    path('admin/modify/', admin_view.admin_modify, name='admin_modify'),
    # 修改管理员验证
    path('admin/modify/check/', admin_view.admin_modify_check, name='admin_modify_check'),
    # 管理员启用
    path('admin/start/', admin_view.admin_start, name='admin_start'),
    # 管理员停用
    path('admin/stop/', admin_view.admin_stop, name='admin_stop'),
    # 修改密码
    path('admin/pwd_edit/', admin_view.admin_pwd_edit, name='admin_pwd_edit'),
]

# 班级管理
urlpatterns += [
    # 班级列表
    path('classgrade/', admin_view.classgrade, name='classgrade'),
    # 班级添加
    path('classgrade/add/', admin_view.classgrade_add, name='classgrade_add'),
    # 班级添加验证
    path('classgrade/add/check/', admin_view.classgrade_add_check, name='classgrade_add_check'),
    # 班级删除
    path('classgrade/del/', admin_view.classsgrade_del, name='classgrade_del'),
    # 班级修改
    path('classgrade/modify/', admin_view.classgrade_modify, name='classgrade_modify'),
    # 班级修改保存
    path('classgrade/save/', admin_view.classgrade_save, name='classgrade_save'),
    # 班级搜索
    path('classgrade/search/', admin_view.classgrade_search, name='classgrade_search'),
]

# 学员
urlpatterns += [
    # 学员管理
    path('student_list/', admin_view.student_list, name="student_list"),
    # 学员信息修改
    path('student_amend/', admin_view.student_amend, name="student_amend"),
    # 修改判断
    path('student_check/', admin_view.student_check, name="student_check"),
    # 学员删除
    path("student_delete/", admin_view.student_delete, name="student_delete"),
    # 学员搜索判断
    path("student_query/", admin_view.student_query, name="student_query"),
]
# 结业模块
urlpatterns +=[
    # 违纪，处罚页面
    path("violate_punish/", cache_page(10)(admin_view.violate_punish),name="violate_punish"),
    # 违纪，处罚判断
    path("violate_punish_ckeck/", admin_view.violate_punish_ckeck,name="violate_punish_ckeck"),
    # 补贴页面
    path("subsidy/", cache_page(10)(admin_view.subsidy), name="subsidy"),
    # 补贴搜索
    path("subsidy_ckeck/", admin_view.subsidy_ckeck,name="subsidy_ckeck"),
    # 技能成绩页面
    path("skill_grade/", cache_page(10)(admin_view.skill_grade),name="skill_grade"),
    # 技能成绩搜索判断
    path("skill_grade_ckeck/", admin_view.skill_grade_ckeck,name="skill_grade_ckeck"),
    # 职业素养页面
    path("profession_grade/", cache_page(10)(admin_view.profession_grade),name="profession_grade"),
    # 职业素养页面判断
    path("profession_grade_ckeck/", admin_view.profession_grade_ckeck,name="profession_grade_ckeck"),
    # 能力评估页面
    path("appraisal_report/", cache_page(10)(admin_view.appraisal_report),name="appraisal_report"),
    # 能力评估收搜页面
    path("appraisal_report_ckeck/", admin_view.appraisal_report_ckeck,name="appraisal_report_ckeck"),
    # 能力评估详细
    path("appraisal_detail/", admin_view.appraisal_detail,name="appraisal_detail"),
    # 访谈记录页面
    path("interview_record/", cache_page(10)(admin_view.interview_record),name="interview_record"),
    # 访谈记录收搜判断
    path("interview_record_ckeck/",admin_view.interview_record_ckeck,name="interview_record_ckeck")
]

qyedu/qyedu/urls.py
# coding=utf8
# from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    # 授课
    path('give_lessons/', include('give_lessons.urls')),
    # 后台
    path('new_admin/', include('new_admin.urls')),
    # 学习
    path('study/', include('study.urls')),
    # 人才库
    path('talent_all/', include('talent_all.urls')),
    # path('admin/', admin.site.urls),
    # 宿舍
    path('dormitory/', include("dormitory.urls")),
    # 考试
    path('examination/', include("examination.urls")),
    # 第三方模块验证码相关
    path('captcha/', include('captcha.urls')),
    # 招生
    path('recruit_students/', include('recruit_students.urls')),
    # 就业
    path('job/', include('obtain_employment.urls')),
    # 训练营
    path('star/', include('six_group.urls')),
    # 访谈
    path('interview/', include('interview.urls')),
    # 评测
    path('evaluate/', include('evaluate.urls')),

]


urlpatterns += [
    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='media')
]

qyedu/study/urls.py
# coding=utf8

from django.urls import path, re_path
from . import views

app_name = 'study'
urlpatterns = [
    path('main/', views.stu_main, name='stu_main'),
    path('a/<str:id_juge>', views.student_sign,name='student_sign'),
    path('sign/', views.stu_sign, name='stu_sign'),
    path('sign/add/', views.stu_add, name='stu_add'),
    path('self/show/', views.self_show, name='self_show'),
    path('qian/selfshow/', views.qian_selfshow, name='qian_selfshow'),
    path('self/add/', views.self_add, name='self_add'),
    path('self/modify/', views.self_modify, name='self_modify'),
    path('stuweek/add/', views.stuweek_add, name='stuweek_add'),
    path('qianweek/', views.qianweek, name='qianweek'),
    # path('qianweek/modify/', views.qianweek_modify, name='qianweek_modify'),
    path('stuweek/show/', views.stuweek_show, name='stuweek_show'),
    path('stuweek/modify/', views.stuweek_modify, name='stuweek_modify'),
]

qyedu/study/models.py
"""
学习模块
"""
from django.db import models
from account.models import NewUser
from give_lessons.models import LessonsPlan
import time
import datetime

# Create your models here.
class SignIn(models.Model):
    choices = (
        (1, '上午签到'),
        (2, '下午签到'),
        (3, '晚上签到'),
        (4, '晚上放学签到'),
        (5, '迟到/早退')
    )
    sign_in = models.IntegerField(choices=choices)
    date_time = models.DateTimeField(auto_now_add=True)
    my_ip = models.CharField(max_length=30, default='127.0.0.1')
    student_id = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    is_del = models.IntegerField(default=0)

    class Meta:
        db_table = 'sign_in'


class WeekendSummarize(models.Model):
    content = models.CharField(max_length=500)
    student_id = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    publish_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(blank=True, null=True, auto_now=True)
    score = models.PositiveIntegerField(null=True, blank=True)
    score_date = models.DateTimeField(null=True, blank=True)
    is_del = models.IntegerField(default=0)

    class Meta:
        db_table = 'weekend_summarize'

    def is_expire(self):
        """
        只能修改当周发布内容
        :return:
        """
        return datetime.datetime.now().year == self.publish_date.year \
            and datetime.datetime.now().isocalendar()[1] == self.publish_date.isocalendar()[1]



class Evaluate(models.Model):
    student_id = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    evaluete_content = models.CharField(max_length=200)
    plub_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)
    give_les = models.ForeignKey(LessonsPlan, on_delete=models.DO_NOTHING)
    is_del = models.IntegerField(default=0)
    knowledges = models.CharField(max_length=500)


    class Meta:
        db_table = 'evaluate'

    def is_expire(self):
        """
        只能修改当周发布的意见反馈
        :return:
        """
        return datetime.datetime.now().year == self.plub_date.year and datetime.datetime.now().month == self.plub_date.month and datetime.datetime.now().day == self.plub_date.day

qyedu/study/templates/study/qian_self_show.html
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css" href="{% static "h-ui/css/H-ui.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/H-ui.admin.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "lib/Hui-iconfont/1.0.8/iconfont.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/skin/default/skin.css" %}" id="skin" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/style.css" %}" />
<!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<title>自我评价</title>
</head>
<body>

<div class="page-container">
	<div class="cl pd-5 bg-1 bk-gray mt-20">
		<span class="l">
		<a class="btn {% if expire == 0 %}btn-primary{% else %}disabled{% endif %} radius"  href="{% url 'study:self_add' %}"><i class="Hui-iconfont">&#xe600;</i> 添加评价</a>
        <a style="display: none;" class="btn btn-primary radius" href="{% url 'study:stu_main' %}">返回主页面</a>
		</span>
		<span class="r">共有数据：<strong>{{ selfs.count}}</strong> 条</span>
	</div>
	<div class="mt-20">
		<table class="table table-border table-bordered table-hover table-bg table-sort">
			<thead>
				<tr class="text-c">
					<th width="25"><input type="checkbox" name="" value=""></th>
                    <th width="50">序号</th>
                    <th width="150">讲师</th>
                    <th width="150">授课计划</th>
                    <th>掌握程度评价</th>
					<th width="250">意见反馈</th>
					<th width="150">操作</th>
				</tr>
			</thead>
			<tbody>
            {% for self in selfs %}
                    <tr class="text-c">
					    <td><input type="checkbox" name="" value=""></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ self.give_les.teacher_id.realname }}</td>
                        <td>{{ self.give_les.les_plan|slice:'20' }}</td>
                        <td>
                            {% autoescape off %}
                        {{ self.knowledges }}
                            {% endautoescape %}
                        </td>
					    <td >{{ self.evaluete_content|slice:'30' }}</td>
					    <td class="f-14"><a title="编辑" href="{% url "study:self_modify" %}?c_id={{ self.id }}" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a></td>
				    </tr>
            {% endfor %}

			</tbody>
		</table>
	</div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static "lib/jquery/1.9.1/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "lib/layer/2.4/layer.js" %}"></script>
<script type="text/javascript" src="{% static "h-ui/js/H-ui.min.js" %}"></script>
<script type="text/javascript" src="{% static "h-ui.admin/js/H-ui.admin.js" %}"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="{% static "lib/My97DatePicker/4.8/WdatePicker.js" %}"></script>
<script type="text/javascript" src="{% static "lib/datatables/1.10.0/jquery.dataTables.min.js" %}"></script>
<script type="text/javascript" src="{% static "lib/laypage/1.2/laypage.js" %}"></script>
<script type="text/javascript">

    {% if messages %}
        {% for message in messages %}
            alert('{{ message }}', 1000);
        {% endfor %}
    {% endif %}


$('.table-sort').dataTable({
	"aaSorting": [[ 1, "desc" ]],//默认第几个排序
	"bStateSave": true,//状态保存
	"aoColumnDefs": [
	  //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
	  {"orderable":false,"aTargets":[0,6]}// 制定列不参与排序
	]
});
/*系统-栏目-添加*/
function system_category_add(title,url,w,h){
	layer_show(title,url,w,h);
}
/*系统-栏目-编辑*/
function system_category_edit(title,url,w,h){
	layer_show(title,url,w,h);
}
/*系统-栏目-删除*/
function system_category_del(obj,id){
	layer.confirm('确认要删除吗？',function(index){
		$.ajax({
			type: 'GET',
			url: '{% url 'new_admin:category_del' %}?c_id='+id,
			dataType: 'json',
			success: function(data){
			    console.log(data.status);
			    if (data.status == 1){
			        console.log(data.status);
                       $(obj).parents("tr").remove();
				        layer.msg('已删除!',{icon:1,time:1000});
                    }else {
                        layer.msg("删除失败!!!",{icon:6,time:1000});
                    }
			},
            error:function(data) {
                console.log(data.status);
                },
		});
	});
}
</script>
</body>
</html>

qyedu/study/templates/study/qian_sign.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'study/css/stuweek.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static "h-ui/css/H-ui.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/H-ui.admin.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "lib/Hui-iconfont/1.0.8/iconfont.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/skin/default/skin.css" %}" id="skin" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/style.css" %}" />
    </head>
    <body>
	<div class="cl pd-5 bg-1 bk-gray mt-20 qian_sign">
		<span class="l">
			<a class="btn radius sign" href="{% url 'study:stu_add' %}?cli_date={% now 'H:i:s'%}"><i class="Hui-iconfont">&#xe600;</i> 签到</a>
			<a class="btn btn-primary radius" href="{% url 'study:stu_main' %}">返回主页面</a>
		</span>
		<span class="r">共有数据：<strong>{{ stu_signs.count}}</strong> 条</span>
	</div>
	<div class="mt-20">
		<table class="table table-border table-bordered table-hover table-bg table-sort">
			<thead>
				<tr class="text-c">
					<th width="25"><input type="checkbox" name="" value=""></th>
                    <th width="50">序号</th>
                    <th width="150">签到</th>
					<th width="200">签到时间</th>
				</tr>
			</thead>
			<tbody>
            {% for sign in stu_signs %}
                <tr class="text-c">
                    <td><input type="checkbox" name="" value=""></td>
                    <td>{{ forloop.counter }}</td>
                    <td>
                    {{ sign.get_sign_in_display }}
                    </td>
                    <td >{{ sign.date_time|date:'Y-m-d H:i:s' }}</td>
                </tr>
            {% endfor %}
			</tbody>
		</table>
	</div>
    </body>
</html>
<script src="{% static 'study/js/jquery-3.3.1.js' %}"></script>
<script>
    {% if messages %}
        {% for message in messages %}
            alert('{{ message }}', 1000);
        {% endfor %}
    {% endif %}

    // var myDate = new Date();
    // myTime = myDate.getHours() + ":" + myDate.getMinutes() + ":" + myDate.getSeconds();
    // if((myTime >= '08:00:00' && myTime <= '08:30:00')
    //  || (myTime >= '13:00:00' && myTime <= '13:30:00')
    //  || (myTime >= '18:30:00' && myTime <= '19:00:00')
    //  || (myTime >= '21:00:00' && myTime <= '22:00:00')) {
    //     $('.sign').toggleClass('disabled btn-primary');
    // } else {
    //     $('.sign').removeClass('btn-primary');
    // }

    if('{{ id_juge }}' == '1') {
        $('.sign').addClass('disabled').removeClass('btn-primary');
    }


</script>

qyedu/study/templates/study/qian_stuweek.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'study/css/stuweek.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static "h-ui/css/H-ui.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/H-ui.admin.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "lib/Hui-iconfont/1.0.8/iconfont.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/skin/default/skin.css" %}" id="skin" />
<link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/style.css" %}" />
    </head>
    <body>
    <div class="cl pd-5 bg-1 bk-gray mt-20 qian_sign">
        <span class="l">
            <a class="btn {% if expire == 0 %}btn-primary{% else %}disabled{% endif %} radius"  href='{% url 'study:stuweek_add' %}'><i class="Hui-iconfont">&#xe600;</i> 添加总结</a>
            <a class="btn btn-primary radius" href="{% url 'study:stu_main' %}">返回主页面</a>

        </span>
        <span class="r">共有数据：<strong>{{ stuweeks.count}}</strong> 条</span>
    </div>
        <table class="table table-border table-bordered table-hover table-bg table-sort">
            <thead>
                <tr class="text-c">
                    <th width="10">序号</th>
                    <th width="50">内容</th>
                    <th width="20">发布日期</th>
                    <th width="20">分数</th>
                    <th width="20">修改</th>
                </tr>
            </thead>
            <tbody>
            {% for stuweek in stuweeks %}
                <tr class="text-c">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ stuweek.content|slice:'50' }}</td>
                    <td class="pub_date">{{ stuweek.publish_date|date:'Y-m-d h:i:s' }}</td>
                    <td>{% if stuweek.score %}{{ stuweek.score }}{% endif %}</td>
                   <td class="f-14"> {% if stuweek.is_expire %}<a title="编辑" href='{% url "study:stuweek_modify" %}?c_id={{ stuweek.id }}'  style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>{% else %}不可编辑{% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </body>
</html>
<script src="{% static 'study/js/jquery-3.3.1.js' %}"></script>
<script>
    {% if messages %}
        {% for message in messages %}
            alert('{{ message }}', 1000);
        {% endfor %}
    {% endif %}
</script>

qyedu/study/templates/study/sign_show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

qyedu/study/templates/study/stu_main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        <h1>学生个人界面</h1>
        <p>欢迎回来</p>
        <a href="{% url 'study:student_sign' 0 %}">前往签到</a>
        <a href="{% url 'study:qianweek' %}">周末总结</a>
        <a href="{% url 'study:qian_selfshow' %}">自我评价</a>
        <a href="">退出</a>
    </body>
</html>