qyedu/qyedu/urls.py
# coding=utf8
# from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    # 授课
    path('give_lessons/', include('give_lessons.urls')),
    # 后台
    path('new_admin/', include('new_admin.urls')),
    # 学习
    path('study/', include('study.urls')),
    # 人才库
    path('talent_all/', include('talent_all.urls')),
    # path('admin/', admin.site.urls),
    # 宿舍
    path('dormitory/', include("dormitory.urls")),
    # 考试
    path('examination/', include("examination.urls")),
    # 第三方模块验证码相关
    path('captcha/', include('captcha.urls')),
    # 招生
    path('recruit_students/', include('recruit_students.urls')),
    # 就业
    path('job/', include('obtain_employment.urls')),
    # 训练营
    path('star/', include('six_group.urls')),
    # 访谈
    path('interview/', include('interview.urls')),
    # 评测
    path('evaluate/', include('evaluate.urls')),

]


urlpatterns += [
    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='media')
]

qyedu/recruit_students/urls.py
from django.urls import path
from . import views

app_name = 'recruit_students'
urlpatterns = [
    # 跟进状态
    path('followup_state/',views.followup_state,name='followup_state'),
    # 跟进状态记录添加
    path('followup_add/', views.followup_add,name='followup_add'),
    # 跟进状态保存
    path('followup_save/',views.followup_save,name='followup_save'),
    # 跟进状态编辑
    path('followup_edit/',views.followup_edit,name='followup_edit'),
    # 跟进状态编辑保存
    path('followup_edit_save/',views.followup_edit_save,name='followup_edit_save'),
    # 跟进状态删除
    path('followup_del/',views.followup_del,name='followup_del'),
    # 跟进状态搜索
    path('followup_search/',views.followup_search,name='followup_search'),

    # 生源录入
    path('input/', views.input, name='input'),
    # 生源添加
    path('add/',views.add_students,name='add_students'),
    # 生源添加验证
    path('add/check/',views.add_students_check,name='add_students_check'),
    # 生源删除
    path('del/', views.del_student,name='del_student'),
    # 生源信息修改
    path('modify/', views.modify_student,name='modify_student'),
    # 生源信息修改验证
    path('modify/check/', views.student_modify_check,name='student_modify_check'),
    # 生源信息搜索
    path('search/', views.student_search,name='student_search'),
    # 生源分发页面
    path('distribution/', views.students_distribute, name='students_distribute'),
    path('distribution/to_person/', views.dis_to_person, name='dis_to_person'),
]

qyedu/account/models.py
from django.db import models
from django.contrib.auth.models import User


class UserRole(models.Model):
    """
    用户角色表。
    """
    role_name = models.CharField(max_length=20)

    def __str__(self):
        return self.role_name


class NewUser(models.Model):
    """
    用户资料表
    """
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    realname = models.CharField(max_length=15)
    role = models.ForeignKey(UserRole, on_delete=models.DO_NOTHING)
    mobile_number = models.CharField(max_length=15)
    id_card = models.CharField(max_length=25)
    birthday = models.DateField(null=True, blank=True)
    info = models.TextField()
    choice = (
        (0,'女'),
        (1,'男'),
    )
    gender = models.PositiveSmallIntegerField(choices=choice, default=1)
    edu_level = models.CharField(max_length=100)
    home_address = models.CharField(max_length=100)
    choice_s = (
        (0,'未激活'),
        (1,'已激活'),
        (2,'结业'),
        (3,'退学')
    )
    state = models.PositiveSmallIntegerField(choices=choice_s, default=0)
    choice_is = (
        (0,'否'),
        (1,'是'),
    )
    is_goodman = models.PositiveSmallIntegerField(choices=choice_is, default=0)
    choice_del = (
        (0,'正常'),
        (1,'删除'),
    )
    is_del = models.PositiveSmallIntegerField(choices=choice_del, default=0)
    choice_pay = (
        (0, '未设定'),
        (1, '贷款缴费'),
        (2, '现金缴费')
    )
    pay_mode = models.PositiveSmallIntegerField(choices=choice_pay, default=0)

    def __str__(self):
        return self.realname

qyedu/recruit_students/models.py
"""
招生模块
"""
# coding=utf8
from django.db import models
from account.models import UserRole, NewUser


class Followup_state(models.Model):
    '''
    跟进状态记录
    '''
    # 跟进学生
    f_s_name = models.ForeignKey(NewUser, on_delete=models.DO_NOTHING, related_name='f_s_name')
    # 跟进描述
    f_info = models.CharField(max_length=200)
    # 跟进时间
    f_date = models.DateField(auto_now_add=True)
    #  录入人
    f_record_person = models.ForeignKey(NewUser, on_delete=models.DO_NOTHING, related_name='f_record_person')
    # 录入时间
    add_time = models.DateTimeField(auto_now_add=True)


class Source_distribution(models.Model):
    '''
    生源分配表
    '''
    # 学生
    student = models.ForeignKey(NewUser, on_delete=models.CASCADE, related_name='sd_student')
    # 咨询顾问`
    consultant = models.ForeignKey(NewUser, on_delete=models.CASCADE, related_name='sd_consultants')

qyedu/recruit_students/forms.py
from django import forms
from .models import Followup_state

class FollowForm(forms.ModelForm):
    class Meta:
        model = Followup_state
        fields = ['f_info']
        widgets = {
            'f_info': forms.Textarea(attrs={'class':'textarea','onkeyup':'$(this).Huitextarealength(this,200)','id':'info'}),
        }

qyedu/recruit_students/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from account.models import UserRole,NewUser
from django.http import JsonResponse, HttpResponseRedirect
from .models import Followup_state
from .forms import FollowForm
from .models import Source_distribution


def followup_state(request):
    '''
    跟进状态录入
    :param request:
    :return:
    '''
    followup_states = Followup_state.objects.all()
    return render(request,'recruit_students/followup_state.html',locals())


def followup_add(request):
    '''
    跟进状态添加
    :param request:
    :return:
    '''
    user = request.user
    new_user = NewUser.objects.get(user=user)
    role = new_user.role
    students = NewUser.objects.filter(role=2)
    return render(request,'recruit_students/followup_add.html',locals())


def followup_save(request):
    '''
    跟进描述保存
    :param request:
    :return:
    '''
    user = request.user
    new_user = NewUser.objects.get(user=user)
    role = new_user.role
    if request.method == 'POST':
        if role in UserRole.objects.filter(Q(role_name='院校经理') | Q(role_name='咨询顾问')| Q(role_name='超级管理员')):
            followup_state = Followup_state()
            info = request.POST['info']
            s_id = request.POST['student_id']
            if Followup_state.objects.filter(pk=s_id).exists():
                messages.info(request,'该学生跟进状态已录入')
                return redirect(reverse('recruit_students:followup_add'))
            else:
                followup_state.f_s_name_id = s_id
                followup_state.f_record_person_id = role.id
                followup_state.f_info = info
                followup_state.save()
                return redirect(reverse('recruit_students:followup_state'))
        else:
            return redirect(reverse('recruit_students:followup_state'))
    else:
        return redirect(reverse('recruit_students:followup_state'))
    

def followup_edit(request):
    '''
    跟进状态编辑
    :param request:
    :return:
    '''
    s_id = request.GET.get('s_id')
    if s_id is None:
        return redirect(reverse('recruit_students:followup_state'))
    if not s_id.isdigit():
        return redirect(reverse('recruit_students:followup_state'))
    if s_id.isdigit():
        try:
            followup_state = Followup_state.objects.get(pk=s_id)
        except Followup_state.DoesNotExist:
            return redirect(reverse('recruit_students:followup_state'))
    form = FollowForm(instance=followup_state)
    return render(request,'recruit_students/followup_edit.html',locals())


def followup_edit_save(request):
    '''
    跟进状态编辑保存
    :param request:
    :return:
    '''
    if request.method == 'POST':
        user = request.user
        s_id = request.POST.get('s_id')
        if s_id is None:
            return redirect(reverse('recruit_students:followup_state'))
        if not s_id.isdigit():
            return redirect(reverse('recruit_students:followup_state'))
        try:
            followup_state = Followup_state.objects.get(pk=s_id)
        except Followup_state.DoesNotExist:
            return redirect(reverse('recruit_students:followup_state'))
        form = FollowForm(request.POST,instance=followup_state)
        if form.is_valid():
            form.save()
    return redirect(reverse('recruit_students:followup_state'))


def followup_del(request):
    '''
    跟进状态删除
    :param request:
    :return:
    '''
    id = request.GET.get('id')
    if id is None:
        return JsonResponse({'status':0,'msg':'删除失败'})
    if not id.isdigit():
        return JsonResponse({'status':2,'msg':'删除失败'})
    if id.isdigit():
        try:
            followup_state = Followup_state.objects.get(pk=id)
        except Followup_state.DoesNotExist:
            return JsonResponse({'status': 0, 'msg': '删除失败'})
        followup_state.delete()
        return JsonResponse({'status':1,'msg':'删除成功'})


def followup_search(request):
    '''
    跟进状态搜索
    :param request:
    :return:
    '''
    if request.method == 'POST':
        search = request.POST.get('search')
        if search:
            followup_states = Followup_state.objects.filter(f_s_name__realname__contains=search)
        else:
            followup_states = Followup_state.objects.all()
    return render(request, 'recruit_students/followup_state.html', locals())


@login_required(login_url='new_admin:login')
def input(request):
    '''
    生源录入页面（列表）
    :param request:
    :return:
    '''
    students = NewUser.objects.filter(state=0, role=2, is_del=0)
    login_user = NewUser.objects.get(user=request.user)
    return render(request, 'recruit_students/students.html', locals())


@login_required(login_url='new_admin:login')
def add_students(request):
    '''
    生源录入页面（添加窗口)
    :param request:
    :return:
    '''
    return render(request,'recruit_students/students_add.html',locals())


def add_students_check(request):
    '''
    生源录入页面学员添加验证
    :param request: 
    :return: 
    '''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        realname = request.POST.get('realname')
        email = request.POST.get('email')
        gender = request.POST.get('gender')
        info = request.POST.get('info')
        id_card = request.POST.get('id_card')
        birthday = request.POST.get('birthday')
        edu_level = request.POST.get('edu_level')
        home_address = request.POST.get('home_address')
        mobile_number = request.POST.get('mobile_number')
        if username == '' or User.objects.filter(username=username).exists():
            messages.info(request, '账号不能为空或已存在')
            return redirect('recruit_students:input')
        if password == '' or password2 == '' or password != password2:
            messages.info(request, '密码不能为空或两次输入密码不一致')
            return redirect('recruit_students:input')
        if realname == '':
            messages.info(request, '真实姓名不能为空')
            return redirect('recruit_students:input')
        if email == '':
            messages.info(request, '邮箱账号不能为空')
            return redirect('recruit_students:input')
        if info == '':
            messages.info(request, '简介不能为空')
            return redirect('recruit_students:input')
        if id_card == '' or NewUser.objects.filter(id_card=id_card).exists():
            messages.info(request, '身份账号不能为空或格式不正确或身份号已存在')
            return redirect('recruit_students:input')
        if home_address == '':
            messages.info(request, '家庭地址不能为空')
            return redirect('recruit_students:input')
        if mobile_number == '' or NewUser.objects.filter(mobile_number=mobile_number).exists():
            messages.info(request, '手机号不能为空或格式不正确或手机号已存在')
            return redirect('recruit_students:input')
        user = User.objects.create_user(username=username, password=password, email=email, is_staff=1, is_active=1)
        NewUser.objects.create(realname=realname, mobile_number=mobile_number, gender=gender, info=info,
                                          id_card=id_card, birthday=birthday, edu_level=edu_level,
                                          home_address=home_address, role_id=2, user_id=user.id)
        messages.info(request, '添加成功')
        return redirect('recruit_students:input')
    return redirect('recruit_students:input')


def del_student(request):
    '''
    生源删除
    :param request:
    :return:
    '''
    if request.session.get('hid', False):
        a = request.GET.get('a')
        b = request.GET.get('b')
        if User.objects.filter(id=b).exists():
            user = User.objects.get(id=b)
            user.is_active = 0
            user.save()
            if NewUser.objects.filter(id=a).exists():
                new_user = NewUser.objects.get(id=a)
                new_user.is_del = 1
                new_user.save()
                return JsonResponse({'status': 1})
            return JsonResponse({'status': 0})
        return JsonResponse({'status': 0})
    return HttpResponseRedirect(reverse('new_admin:login'))


@login_required(login_url='new_admin:login')
def modify_student(request):
    '''
    生源录入页面学员信息编辑页面
    :param request:
    :return:
    '''
    if request.session.get('hid', False):
        c = request.GET.get('c_id')
        if NewUser.objects.filter(id=c).exists():
            new_user = NewUser.objects.get(id=c)
            user = User.objects.get(id=new_user.user_id)
            return render(request, 'recruit_students/students_modify.html', {'user': user, 'new_user': new_user})
        else:
            messages.info(request, '此用户不存在')
            return render(request, 'recruit_students/students_modify.html')
    return HttpResponseRedirect(reverse('new_admin:login'))


def student_modify_check(request):
    """
    生源录入页面学生信息修改
    :param request:
    :return:
    """
    if request.method == 'POST':
        realname = request.POST.get('realname')
        id_card = request.POST.get('id_card')
        email = request.POST.get('email')
        info = request.POST.get('info')
        gender = request.POST.get('gender')
        print("性别是。。。")
        print(gender)
        edu_level = request.POST.get('edu_level')
        home_address = request.POST.get('home_address')
        mobile_number = request.POST.get('mobile_number')
        birthday = request.POST.get('birthday')
        user_id = request.POST.get('user_id')
        new_user_id = request.POST.get('new_user_id')
        if User.objects.filter(id=user_id).exists() and NewUser.objects.filter(id=new_user_id).exists():
            user = User.objects.get(id=user_id)
            new_user = NewUser.objects.get(id=new_user_id)

qyedu/recruit_students/templates/recruit_students/followup_state.html
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
	<meta http-equiv="Cache-Control" content="no-siteapp" />
	<link rel="stylesheet" type="text/css" href="../../static/h-ui/css/H-ui.min.css" />
	<link rel="stylesheet" type="text/css" href="../../static/h-ui.admin/css/H-ui.admin.css" />
	<link rel="stylesheet" type="text/css" href="../../static/lib/Hui-iconfont/1.0.8/iconfont.css" />
	<link rel="stylesheet" type="text/css" href="../../static/h-ui.admin/skin/default/skin.css" id="skin" />
	<link rel="stylesheet" type="text/css" href="../../static/h-ui.admin/css/style.css" />
	<title>跟进状态列表</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 跟进状态管理 <span class="c-gray en">&gt;</span> 跟进状态列表 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="page-container">
	<form action="{% url 'recruit_students:followup_search' %}" method="post">
        {% csrf_token %}
        <div class="text-c">
			<button onclick="removeIframe()" class="btn btn-primary radius">关闭选项卡</button>
            <input value="{{ search }}" type="text" name="search" id="search" placeholder="请输入搜索内容" style="width:250px" class="input-text">
			<button   class="btn btn-success" type="submit"><i class="Hui-iconfont">&#xe665;</i> 搜索</button>
        </div>
    </form>
	<div class="cl pd-5 bg-1 bk-gray mt-20">
		<span class="l">
			<a class="btn btn-primary radius" data-title="添加状态" data-href="{% url 'recruit_students:followup_add' %}" onclick="Hui_admin_tab(this)" href="javascript:;">
				<i class="Hui-iconfont">&#xe600;</i> 添加状态
			</a>
		</span>
		<span class="r">共有数据：<strong>{{ followup_states.count }}</strong> 条</span> </div>
	<div class="mt-20">
		<table class="table table-border table-bordered table-bg table-hover table-sort table-responsive">
			<thead>
            <tr class="text-c">
                <th width="25"><input type="checkbox" name="" value=""></th>
                <th>ID</th>
                <th width="80">跟进学生</th>
                <th>跟进描述</th>
                <th>跟进时间</th>
                <th>录入人</th>
                <th>录入时间</th>
                <th width="100">操作</th>
            </tr>
            </thead>
            <tbody>
			{% for state in followup_states %}
            <tr class="text-c">
                <td><input type="checkbox" name="" value=""></td>
                <td>{{ state.id }}</td>
                <td>{{ state.f_s_name }}</td>
                <td>{{ state.f_info|safe }}</td>
                <td>{{ state.f_date | date:'Y-m-d'}}</td>
                <td>{{ state.f_record_person }}</td>
                <td> {{ state.add_time | date:'Y-m-d'}} </td>
                <td class="f-14">
                    <a title="编辑" href="{% url 'recruit_students:followup_edit' %}?s_id={{ state.id }}" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>
                    <a title="删除" onclick="article_del(this,'{{ state.id }}')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a>
                </td>
            </tr>
			{% endfor %}
		</table>
	</div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="../../static/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="../../static/lib/layer/2.4/layer.js"></script>
<script type="text/javascript" src="../../static/h-ui/js/H-ui.min.js"></script>
<script type="text/javascript" src="../../static/h-ui.admin/js/H-ui.admin.js"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="../../static/lib/My97DatePicker/4.8/WdatePicker.js"></script>
<script type="text/javascript" src="../../static/lib/datatables/1.10.0/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="../../static/lib/laypage/1.2/laypage.js"></script>
<script type="text/javascript">
    $('.table-sort').dataTable({
        "aaSorting": [[ 1, "desc" ]],//默认第几个排序
        "bStateSave": true,//状态保存
        "pading":false,
        "aoColumnDefs": [
            //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
            {"orderable":false,"aTargets":[0,2]}// 不参与排序的列
        ]
    });

    /*资讯-删除*/
    function article_del(obj,id){
        layer.confirm('确认要删除吗？',function(index){
            $.ajax({
                type: 'GET',
                url: '{% url "recruit_students:followup_del" %}?id=' + id,
                dataType: 'json',
                success: function(data){
                    if (data.status == 1) {
                        $(obj).parents("tr").remove();
                        layer.msg(data.msg,{icon:1,time:1000},
                     	function() {
                            location.reload();
                        });
                    }else {
                        layer.msg(data.msg,{icon:1,time:1000});
                    }
                },
                error:function(data) {
                    console.log(data.msg);
                },
            });
        });
    }


</script>
</body>
</html>

qyedu/recruit_students/templates/recruit_students/students.html
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->
    <link rel="stylesheet" type="text/css" href="{% static "h-ui/css/H-ui.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/H-ui.admin.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "lib/Hui-iconfont/1.0.8/iconfont.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/skin/default/skin.css" %}" id="skin" />
    <link rel="stylesheet" type="text/css" href="{% static "h-ui.admin/css/style.css" %}" />
    <!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
    <title>招生管理</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页
    <span class="c-gray en">&gt;</span>
    招生管理
    <span class="c-gray en">&gt;</span>
    学员管理
    <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a>
</nav>
<div class="page-container">
    <div class="text-c">
        <form action="{% url 'recruit_students:student_search' %}" method="post">
            {% csrf_token %}
            日期范围：
            <input type="text" name="start_time" value="{{ start_time }}"  onfocus="WdatePicker()" id="datemin" class="input-text Wdate" style="width:120px;" autocomplete="off">
            -
            <input type="text" name="end_time" value="{{ end_time }}" onfocus="WdatePicker()" id="datemax" class="input-text Wdate" style="width:120px;" autocomplete="off">
            <input type="text" name="name" id="" placeholder="学生姓名" style="width:250px" class="input-text" value="{{ name }}">
            <button name="" id="" class="btn btn-success" type="submit"><i class="Hui-iconfont">&#xe665;</i> 搜索</button>
        </form>
    </div>
    <div class="cl pd-5 bg-1 bk-gray mt-20">
		<span class="l">
            {% if login_user.role.role_name == "超级管理员" or login_user.role.role_name == "院校经理" %}
                <a class="btn btn-primary radius" onclick="system_student_add('添加学员','{% url 'recruit_students:add_students' %}')" href="javascript:;"><i class="Hui-iconfont">&#xe600;</i> 添加学员</a>
            {% endif %}
		</span>
        <span class="r">共有数据：<strong>{{ students.count}}</strong> 条</span>
    </div>
    <div class="mt-20">
        <table class="table table-border table-bordered table-hover table-bg table-sort">
            <thead>
            <tr class="text-c">
                <th width="25"><input type="checkbox" name="" value=""></th>
                <th width="80">序号</th>
                <th width="70">学员姓名</th>
                <th>性别</th>
                <th>身份证号</th>
                <th>出生日期</th>
                <th width="80">手机号</th>
                <th>学历</th>
                <th>家庭住址</th>
                <th width="100">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for stu in students %}
                <tr class="text-c">
                    <th width="25"><input type="checkbox" name="" value=""></th>
                    <td>{{ stu.id }}</td>
                    <td>{{ stu.realname }}</td>
                    <td class="text-l">{{ stu.get_gender_display}}</td>
                    <td>{{ stu.id_card }}</td>
                    <td>{{ stu.birthday | date:'Y-m-d' }}</td>
                    <td>{{ stu.mobile_number }}</td>
                    <td>{{ stu.edu_level }}</td>
                    <td>{{ stu.home_address }}</td>
                     <td class="f-14"><a title="编辑" href="javascript:;" onclick="system_student_edit('学生编辑','{% url 'recruit_students:modify_student' %}?c_id={{ stu.id }}','1','800','700')" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>
                        <a title="删除" href="javascript:;" onclick="system_student_del(this,'{{ stu.id }}','{{ stu.user_id }}')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a></td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static "lib/jquery/1.9.1/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "lib/layer/2.4/layer.js" %}"></script>
<script type="text/javascript" src="{% static "h-ui/js/H-ui.min.js" %}"></script>
<script type="text/javascript" src="{% static "h-ui.admin/js/H-ui.admin.js" %}"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="{% static "lib/My97DatePicker/4.8/WdatePicker.js" %}"></script>
<script type="text/javascript" src="{% static "lib/datatables/1.10.0/jquery.dataTables.min.js" %}"></script>
<script type="text/javascript" src="{% static "lib/laypage/1.2/laypage.js" %}"></script>
<script type="text/javascript">

    {% if messages %}
        {% for message in messages %}
            $.Huimodalalert('{{ message }}', 1000);
        {% endfor %}
    {% endif %}


    $('.table-sort').dataTable({
        "aaSorting": [[ 1, "desc" ]],//默认第几个排序
        "bStateSave": true,//状态保存
        "aoColumnDefs": [
            //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
            {"orderable":false,"aTargets":[0,8]}// 制定列不参与排序
        ]
    });
    /*系统-班级-添加*/
    function dorm_add(title,url,w,h){
        layer_show(title,url,w,h);
    }
    /*系统-班级-编辑*/
    function dorm_edit(title,url,id,w,h){
        layer_show(title,url,w,h);
    }
    /*学员-删除*/
    function system_student_del(obj,id1,id2){
        layer.confirm('确认要删除吗？',function(index){
            $.ajax({
                type: 'GET',
                url: '{% url "recruit_students:del_student" %}?a=' + id1 + '&b=' + id2,
                dataType: 'json',
                success: function(data){
                    if (data.status == 1){
                        $(obj).parents("tr").remove();
                        layer.msg('已删除!',{icon:1,time:1000});
                    }else {
                        layer.msg("删除失败!!!",{icon:6,time:1000});
                    }
                },
                error:function(data) {
                },
            });
        });
    }

    function system_student_add(title, url, w, h){
        layer_show(title,url,w,h);
    }

    function system_student_edit(title, url, id, w, h){
        layer_show(title, url, w, h);
    }
</script>
</body>
</html>